# Generated by Django 3.1.7 on 2021-02-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_news_is_hot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news_images'),
        ),
        migrations.AlterField(
            model_name='video',
            name='content',
            field=models.FileField(upload_to='Videos'),
        ),
    ]
