# Generated by Django 3.1.7 on 2021-03-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_team_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='week',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
