# Generated by Django 3.1.7 on 2021-04-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_favoriteteams'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_date',
            field=models.DateTimeField(default='2021-01-03'),
            preserve_default=False,
        ),
    ]
