# Generated by Django 3.1.7 on 2021-08-10 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_news_news_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RssLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rss_link', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='favoriteteams',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.team'),
        ),
    ]
